name: Pull Request Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      #- name: Setup MSBuild.exe
      #  uses: microsoft/setup-msbuild@v2

      - name: Check Formatting
        run: dotnet format --verify-no-changes

      - name: Execute unit tests
        run: dotnet test
