name: Pull Request Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:

  check-pr:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Check Formatting
        run: dotnet format --verify-no-changes

      - name: Execute unit tests
        run: dotnet test
